### ISSUE TITLE
I get wrong behavior of hearts when I changed start Y position.

### ISSUE THREAD

**Issue by alexanderkhitev** [saidmarouf/FloatingHearts#1]
Hello! I get wrong behavior of hearts when I changed start Y position. Hearts at the first drop down https://monosnap.com/file/HefeT5Aygzj1XaayiOp4RSmPIZ7Xsk . How can I fix it? Please help me

**Comment by saidmarouf** [comment]
Hi. The path generation should be smarter and more adaptable to various Y and X locations. Would welcome a pull request :)

**Comment by alexanderkhitev** [comment]
@saidmarouf Hello! thank you for your answer =)
