### ISSUE TITLE
heart images not changing colour

### ISSUE THREAD

**Issue by unoiatech** [saidmarouf/FloatingHearts#5]
I am trying the demo code in Xcode 9 beta and Swift 4. It shows the only bordered heart image. Images does not change colour. Can you please guide me on this ?

**Comment by unoiatech** [comment]
Got it worked by myself. :)

**Comment by geekstars** [comment]
how to ? @unoiatech

**Comment by pablogeek** [comment]
@unoiatech Can you please post the solution?
